version: '3.9'

services:
  maria-db:
    image: mariadb:10
    container_name: maria-db
    restart: unless-stopped
    env_file: .env
    environment:
      MARIADB_DATABASE: ${MA_DB_NAME}
      MARIADB_USER: ${MA_DB_USER}
      MARIADB_PASSWORD: ${MA_DB_PASSWD}
      MARIADB_ROOT_PASSWORD: ${MA_DB_PASSWD_ROOT}
      MARIADB_INITDB_SKIP_TZINFO: ${MA_DB_TZ}
    volumes:
      - ./.volumes/madb/:/var/lib/mysql:rw
    networks:
      - devnet
    ports:
      - ${MA_DB_PORT}:3306


  postgres-db:
    image: postgres:15
    container_name: posgres-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PSWD}
    volumes:
      - ./.volumes/pgdb/:/var/lib/postgresql/data
    networks:
      - devnet
    ports:
      - ${PG_DB_PORT}:5432


networks:
  devnet:
    name: devnet