version: '3.9'

services:
  maria-db:
    image: mariadb:10
    container_name: maria-db
    restart: unless-stopped
    env_file: .env
    environment:
      MARIADB_DATABASE: ${MA_DB_NAME}
      MARIADB_USER: ${MA_DB_USER}
      MARIADB_PASSWORD: ${MA_DB_PASSWD}
      MARIADB_ROOT_PASSWORD: ${MA_DB_PASSWD_ROOT}
      MARIADB_INITDB_SKIP_TZINFO: ${MA_DB_TZ}
    volumes:
      - ./.volumes/madb/:/var/lib/mysql:rw
    networks:
      - devnet
    ports:
      - ${MA_DB_PORT}:3306


networks:
  devnet:
    name: devnet